[workspace]
members = [
	"remote-wheel-sender",
	"remote-wheel-viewer",
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
