[osc]
	enabled = true
	input.address = "0.0.0.0:0"
	output.address = "127.0.0.1:19794"

[[axis.wheel.input]]
	controller.name = "Controller Name"
	controller.axis = "x"

[axis.wheel.output.osc.on-update]
	"/wheel/rotation" = [ {input=[-450,450]} ]
