# Settings for where OSC messages should be sent to
osc:
  # The address and UDP port to which OSC messages should be sent.
  #
  # This application currently only supports sending to a single address (for now).
  address: 127.0.0.1:19794

  # OSC messages that will be sent prior to any batch of configured input messages is sent
  pre-bundle:
  #   /bundle/start: []

  # OSC messages that will be sent after any batch of configured input messages is sent
  post-bundle:
  #   /bundle/end: []

# A list of inputs the Sender should respond to.
#
# The default configuration only lists a single input, as the Viewer application currently only
# accepts a single input, but the Sender application supports any number of inputs. Additional
# inputs can be configured by adding a new entry (starting with an unindented dash).
inputs:

- !axis
    controller: Controller Name Here # The name of the controller from which to read the input.
    axis: x # The name of the axis whose value to read and send. Possible values: x y z rx ry rz slider dial
    range: [-450, 450] # The range of values which should be sent in the messages defined below.

    # OSC message(s) to send in response to this input. The OSC address of the message will be the key
    # (prior to the colon). Any number of parameters may be listed, either by listing them inside of
    # square brackets (as shown below) or listing them, one per line, preceded with dashes. If this
    # input is to be sent to the Viewer application, this does not need to be changed.
    #
    # Parameters may be specified as follows:
    #
    # - !int 42 (a constant 32-bit integer)
    # - !long 42 (a constant 64-bit integer)
    # - !float 4.2 (a constant 32-bit floating-point value)
    # - !double 4.2 (a constant 64-bit floating-point value)
    # - !bool true (a boolean True value)
    # - !bool false (a boolean True value)
    # - !string Hello (text)
    # - nil (the absence of a value)
    # - inf (a representation of infinity)
    # - input (the value of the axis, as a 32-bit floating-point value)
    #
    # Multiple messages may be listed here, in which case they will all be sent in the order they are listed.
    osc:
      /wheel/rotation: [input]

# The below is not (currently) used by the Viewer application, but is provided as an example of how
# to configure a button input.
- !button
    controller: Controller Name Here # The name of the controller from which to read the input.
    button: 1 # The button number whose state to read and send. Numbered starting with 1.

    # OSC message(s) to send in response to this input. Almost identical in structure to that of an
    # axis, except for two differences:
    #
    # 1. Parameters set to the input will be sent a boolean value (true when  pressed, false when
    #    released).
    # 2. Messages must be specified within either on-change, on-press, or on-release to determine
    #    when they should be sent. Messages will be sent at the following times (in this order):
    #    a. on-press messages are sent once each time the button is pressed
    #    b. on-release messages are sent once each time the button is released
    #    c. on-change messages are sent once each time the button state is changed (press OR released)
    osc:
      on-change:
        /buttons/1/state: [input]

      on-press:
        /buttons/1/pressed: []

      on-release:
        /buttons/1/released: []
