[osc]
enabled = false
input.address = "0.0.0.0:19793"
output.address = "127.0.0.1:19794"

[osc.output.pre-bundle]
# "/pre/bundle" = []

[osc.output.post-bundle]
# "/post/bundle" = []

[vmc]
enabled = true
receive-addr = "127.0.0.1:3332"
send-addr = "127.0.0.1:3333"
report-interval = 15

[vmc.device.wheel]
type = "wheel"
position = [0, 1.3, 0.38]
rotation = [0, 0, 0]
radius = 0.16

[[axis.wheel.input]]
controller.name = "VKBsim Gunfighter MCG Pro Twist"
controller.axis = "x"

[[axis.wheel.input]]
osc.address = "/wheel/rotation"
osc.range = [-450, 450]

[axis.wheel.output.osc.on-change]
"/wheel/rotation" = [{input = [-450, 450]}]

[axis.wheel.output.vmc.on-change]
blendshape.wheel = [0, 100]
device.wheel = [-450, 450]

[[button.shift-up.input]]
controller.name = "VKBsim Gunfighter MCG Pro Twist"
controller.button = 1

[button.shift-up.output.vmc.on-change]
blendshape.shift-up = [0, 100]
device.shift-up = [-450, 450]

[button.shift-up.output.vmc.on-press]
blendshape.shifterx = 0
blendshape.shiftery = 0
device.shifter = 1

[button.shift-up.output.vmc.on-release]
blendshape.shifterx = 50
blendshape.shiftery = 50
device.shifter = 0
